// Descripciones curadas para el diccionario de datos.
// Origen: comentarios inline del SQL, nombres de constraint, CHECKs y
// lectura del modelo de negocio (Chifa Yemheng). Las descripciones son
// inferidas/curadas, NO literales de la base de datos.

export const TABLA_DESC = {
  departamento: "División política de primer nivel (región). Catálogo geográfico base del sistema.",
  provincia: "Provincia o región dentro de un departamento. Segundo nivel de la jerarquía geográfica.",
  distrito: "Distrito dentro de una provincia. Unidad usada para zonas de delivery y ubicación de personas.",
  tipo_identidad: "Catálogo de tipos de documento de identidad (DNI, RUC, CE, pasaporte) con código SUNAT.",
  persona: "Datos de personas naturales: documento, nombres, apellidos, contacto y ubicación.",
  empresa: "Datos de personas jurídicas: RUC, razón social, contacto y domicilio fiscal.",
  cliente: "Cliente del restaurante (natural o jurídico). Acumula puntos de fidelización.",
  cargo: "Catálogo de cargos del local (mozo, cocina, caja, administración, etc.).",
  contrato: "Catálogo de modalidades de contrato laboral.",
  empleado: "Trabajador del local. Une sus datos de persona con cargo, contrato, salario y turno.",
  tipo_usuario: "Catálogo de tipos de usuario del sistema (administrador, mozo, caja, repartidor, cliente).",
  usuario: "Cuenta de acceso al sistema: login, clave cifrada, intentos y bloqueo por seguridad.",
  modulo: "Módulos funcionales del sistema. Agrupan permisos y ordenan el menú de la aplicación.",
  rol: "Rol de seguridad con nivel jerárquico (administrador, supervisor, operativo).",
  permiso: "Permiso atómico por módulo (clave y nombre). Es la unidad que se asigna a los roles.",
  rol_permiso: "Tabla puente que asigna permisos a roles, con indicador de concesión.",
  usuario_rol: "Tabla puente que asigna roles a usuarios, con vigencia de la asignación.",
  auditoria: "Bitácora de auditoría: registra altas, modificaciones, anulaciones y accesos con IP y terminal.",
  ambiente: "Ambiente o zona del local (salón principal, terraza, barra, sala VIP).",
  estado_mesa: "Catálogo de estados de mesa con color, usado en el mapa de mesas.",
  tipo_mesa: "Catálogo de tipos de mesa con su cargo de servicio en porcentaje.",
  mesa: "Mesa del local: número, ambiente, tipo, capacidad y código QR rotativo para carta digital.",
  unidad_medida: "Catálogo de unidades de medida (NIU, KGM, LTR) con código SUNAT.",
  categoria_producto: "Categoría de la carta. Define el área de despacho (cocina o barra) y el orden.",
  producto: "Artículo de la carta (plato preparado, bebida o insumo): precio, costo, stock y disponibilidad.",
  tipo_pedido: "Catálogo de tipos de pedido (en salón, para llevar, delivery) y si exige mesa.",
  estado_pedido: "Catálogo de estados del pedido (abierto, en preparación, servido, facturado, anulado).",
  pedido: "Cabecera de la comanda: cliente, mesa, tipo, estado, importes y marcas de facturación/anulación.",
  detalle_pedido: "Líneas del pedido con producto, cantidad, precio, nota de cocina y estado de preparación.",
  reserva: "Reserva de mesa: cliente, fecha, número de personas, adelanto y situación.",
  pedido_delivery: "Extensión de delivery de un pedido: dirección, contacto, costo de envío y reparto.",
  metodo_pago: "Catálogo de métodos de pago (efectivo, tarjeta, Yape, Plin) con comisión.",
  caja: "Caja registradora del local, con moneda, terminal y estado de apertura.",
  apertura_caja: "Turno de caja (apertura y cierre) con monto inicial, ingresos, egresos y diferencia.",
  tipo_movimiento_caja: "Catálogo de tipos de movimiento de caja (ingreso o egreso) con su signo.",
  concepto_caja: "Catálogo de conceptos de movimiento (venta, devolución, gasto, etc.).",
  serie_documento: "Series de comprobantes por caja (Boleta, Factura, Nota de crédito, Ticket) con correlativo.",
  venta: "Cabecera de la venta: pedido origen, cliente, cajero, turno de caja, importes y anulación.",
  detalle_venta: "Líneas de la venta con producto, cantidad, precio y subtotal.",
  boleta: "Boleta de venta electrónica: serie, número, cliente y estado de aceptación SUNAT.",
  factura: "Factura electrónica a una empresa: serie, número, receptor, vencimiento y estado SUNAT.",
  nota_credito: "Nota de crédito que anula una venta, con referencia al comprobando emitido.",
  pago_venta: "Pagos aplicados a una venta. Permite pago mixto o dividido en varios métodos.",
  movimiento_caja: "Movimiento de efectivo del turno: concepto, método, usuario y vínculo a pedido o venta.",
  receta: "Receta de un producto preparado: qué insumos y en qué cantidad lo componen.",
  movimiento_inventario: "Kardex de inventario: entradas, salidas, ajustes y mermas con stock anterior y nuevo.",
};

// Descripciones globales por nombre de columna (aplican a cualquier tabla).
export const COL_DESC = {
  estado: "Estado lógico del registro: A=Activo, I=Inactivo, E=Eliminado (borrado lógico).",
  nombre: "Nombre de la persona.",
  nombre_comercial: "Nombre comercial de la empresa.",
  razon_social: "Razón social registrada en SUNAT.",
  descripcion: "Descripción del registro.",
  detalle: "Detalle complementario.",
  email: "Correo electrónico de contacto.",
  telefono: "Teléfono de contacto.",
  celular: "Celular (9 dígitos, formato peruano).",
  direccion: "Dirección.",
  clave: "Clave o clave de acceso al módulo.",
  descripcion_corta: "Descripción corta.",
  longitud: "Longitud máxima del documento.",
  abreviatura: "Abreviatura del registro.",
  codigo: "Código interno del producto.",
  codigo_sunat: "Código según el catálogo SUNAT.",
  color: "Color en hexadecimal para el mapa visual.",
  orden: "Orden de presentación.",
  orden_carta: "Posición de la categoría dentro de la carta.",
  precio: "Precio de venta unitario.",
  costo: "Costo unitario del producto.",
  cantidad: "Cantidad de la línea.",
  descuento: "Descuento aplicado.",
  monto: "Monto del registro.",
  saldo: "Saldo pendiente.",
  puntos: "Puntos acumulados del cliente (fidelización).",
  imagen: "Ruta o URL de la imagen del producto.",
  password: "Contraseña del usuario.",
  situacion: "Situación actual del registro.",
  activo: "Indicador de registro activo (S/N).",
  vigente: "Indicador de vigencia (S/N).",
  observaciones: "Observaciones.",
};

// Descripciones por tabla.columna (tienen prioridad sobre el mapa global).
export const COL_DESC_TABLA = {
  "tipo_identidad.codigo_sunat": "Código SUNAT: 1=DNI, 6=RUC, 4=CE, 7=Pasaporte.",
  "persona.id_tipoidentidad": "Tipo de documento de identidad.",
  "persona.n_documento": "Número del documento de identidad.",
  "persona.f_nacimiento": "Fecha de nacimiento.",
  "persona.ap_paterno": "Apellido paterno.",
  "persona.ap_materno": "Apellido materno.",
  "persona.genero": "Género: M=Masculino, F=Femenino, O=Otro.",
  "persona.direccion": "Dirección de la persona.",
  "empresa.ruc": "RUC de la empresa (11 dígitos).",
  "empresa.email": "Correo electrónico de la empresa.",
  "cliente.tipo_cliente": "Tipo de cliente: N=Natural, J=Jurídico.",
  "cliente.id_persona": "Persona natural asociada (cliente natural).",
  "cliente.id_empresa": "Empresa asociada (cliente jurídico).",
  "cliente.codigo_cliente": "Código interno del cliente.",
  "cliente.puntos": "Puntos acumulados por el cliente.",
  "cliente.f_registro": "Fecha de registro del cliente.",
  "cliente.linea_credito": "Línea de crédito del cliente. Columna sin uso (pendiente de eliminación).",
  "empleado.salario": "Salario mensual del empleado.",
  "empleado.turno": "Turno asignado: Mañana, Tarde, Noche o Partido.",
  "empleado.fondo_pension": "Régimen de pension: ONP o AFP.",
  "empleado.n_hijos": "Número de hijos (para ESSALUD).",
  "empleado.essalud": "Número de afiliación a ESSALUD.",
  "empleado.f_ingreso": "Fecha de ingreso al local.",
  "empleado.f_cese": "Fecha de cese de la relación laboral.",
  "usuario.logeo": "Nombre de usuario para iniciar sesión.",
  "usuario.clave": "Contraseña del usuario almacenada como hash SHA-256.",
  "usuario.intentos": "Intentos de acceso fallidos consecutivos.",
  "usuario.bloqueado": "Indica si la cuenta está bloqueada (S/N).",
  "usuario.f_ultimoacceso": "Fecha y hora del último acceso exitoso.",
  "permiso.clave": "Clave del permiso (ej. VEN_ANULAR, CAJ_CERRAR).",
  "permiso.descripcion": "Descripción del permiso (ej. VEN_ANULAR, CAJ_CERRAR).",
  "auditoria.accion": "Acción auditada: INSERT, UPDATE, DELETE, LOGIN, LOGIN_FALLIDO, ANULAR.",
  "auditoria.id_registro": "Identificador del registro afectado en la tabla auditada.",
  "auditoria.n_tabla": "Nombre de la tabla sobre la que se audita.",
  "auditoria.ip": "Dirección IP desde donde se realizó la acción.",
  "auditoria.terminal": "Terminal o estación de trabajo.",
  "mesa.numero": "Número o código visible de la mesa.",
  "mesa.capacidad": "Número de personas que sienta la mesa.",
  "mesa.codigo_qr": "Código QR rotativo de la mesa para acceder a la carta digital.",
  "estado_mesa.descripcion": "Estado de la mesa (Libre, Ocupada, Reservada, Por cobrar).",
  "estado_mesa.color": "Color en hexadecimal para el mapa de mesas.",
  "tipo_mesa.descripcion": "Tipo o nombre de la mesa.",
  "tipo_mesa.cargo_servicio": "Cargo por servicio en porcentaje sobre el consumo.",
  "categoria_producto.area_despacho": "Área que prepara el producto: COCINA o BARRA.",
  "categoria_producto.n_categoriaproducto": "Nombre de la categoría de la carta.",
  "producto.tipo_producto": "Tipo de producto: P=Preparado, B=Bebida/Reventa, I=Insumo.",
  "producto.controla_stock": "Indica si el producto controla stock (S/N).",
  "producto.stock_actual": "Stock actual del producto.",
  "producto.stock_minimo": "Stock mínimo para alerta de reposición.",
  "producto.afecto_igv": "Indica si el producto afecta IGV (S/N).",
  "producto.disponible": "Indica si el producto está disponible (S/N).",
  "producto.tiempo_preparacion": "Tiempo estimado de preparación en minutos.",
  "producto.detalle": "Descripción o presentación del producto.",
  "estado_pedido.descripcion": "Estado del pedido (Abierto, En preparación, Servido, Facturado, Anulado).",
  "estado_pedido.color": "Color del estado para el tablero de comandas.",
  "tipo_pedido.n_tipopedido": "Nombre del tipo de pedido.",
  "tipo_pedido.requiere_mesa": "Indica si el tipo de pedido exige mesa (S/N).",
  "pedido.numero_pedido": "Número correlativo del pedido.",
  "pedido.n_comensales": "Número de comensales del pedido.",
  "pedido.subtotal": "Subtotal del pedido antes de IGV y servicio.",
  "pedido.servicio": "Cargo por servicio aplicado al pedido.",
  "pedido.igv": "Impuesto General a las Ventas del pedido.",
  "pedido.total": "Total a pagar del pedido.",
  "pedido.facturado": "Indica si el pedido fue facturado (S/N).",
  "pedido.anulado": "Indica si el pedido fue anulado (S/N).",
  "pedido.motivo_anulacion": "Motivo de la anulación del pedido.",
  "pedido.f_pedido": "Fecha y hora de registro del pedido.",
  "pedido.f_cierre": "Fecha y hora de cierre del pedido.",
  "pedido.observacion": "Observaciones del pedido.",
  "detalle_pedido.precio_unitario": "Precio unitario del producto al momento del pedido.",
  "detalle_pedido.sub_total": "Subtotal calculado: (cantidad × precio) − descuento.",
  "detalle_pedido.nota_cocina": "Nota para cocina (ej. sin cebolla).",
  "detalle_pedido.estado_preparacion": "Estado de preparación: P=Pendiente, E=En proceso, S=Servido, A=Anulado.",
  "detalle_pedido.es_cortesia": "Indica si la línea es cortesía de la casa (S/N).",
  "detalle_pedido.f_solicitud": "Fecha y hora en que se solicitó la línea.",
  "detalle_pedido.f_atencion": "Fecha y hora en que se atendió la línea.",
  "reserva.situacion": "Situación: P=Pendiente, C=Confirmada, A=Atendida, X=Cancelada.",
  "reserva.n_personas": "Número de personas reservadas.",
  "reserva.adelanto": "Adelanto pagado para reservar la mesa.",
  "pedido_delivery.direccion_entrega": "Dirección de entrega del pedido.",
  "pedido_delivery.referencia": "Referencia de la dirección o punto de entrega.",
  "pedido_delivery.telefono_contacto": "Teléfono de contacto para la entrega.",
  "pedido_delivery.costo_envio": "Costo del envío (delivery).",
  "pedido_delivery.f_salida": "Fecha y hora de salida del repartidor.",
  "pedido_delivery.f_entrega": "Fecha y hora de entrega del pedido.",
  "pedido_delivery.situacion": "Situación: P=Pendiente, R=En ruta, E=Entregado, C=Cancelado.",
  "metodo_pago.afecta_efectivo": "Indica si el método afecta el efectivo de la caja (S/N).",
  "metodo_pago.requiere_referencia": "Indica si el método requiere referencia o voucher (S/N).",
  "metodo_pago.comision": "Comisión del método de pago en porcentaje.",
  "caja.moneda": "Moneda de la caja (ej. PEN).",
  "caja.monto_base": "Monto base con que se abrió la caja.",
  "caja.aperturada": "Indica si la caja está abierta (S/N).",
  "caja.serie_terminal": "Serie o identificador de la terminal de la caja.",
  "apertura_caja.numero_turno": "Número del turno de caja.",
  "apertura_caja.f_apertura": "Fecha y hora de apertura del turno.",
  "apertura_caja.f_cierre": "Fecha y hora de cierre del turno.",
  "apertura_caja.monto_inicial": "Monto inicial con que se aperturó el turno.",
  "apertura_caja.total_ingresos": "Total de ingresos del turno.",
  "apertura_caja.total_egresos": "Total de egresos del turno.",
  "apertura_caja.monto_sistema": "Monto calculado por el sistema.",
  "apertura_caja.monto_declarado": "Monto declarado por el cajero en el arqueo.",
  "apertura_caja.diferencia": "Diferencia entre monto declarado y monto del sistema.",
  "apertura_caja.situacion": "Situación del turno: A=Abierta, C=Cerrada.",
  "tipo_movimiento_caja.signo": "Signo del movimiento: + (ingreso) o − (egreso).",
  "tipo_movimiento_caja.n_tipomovimiento": "Nombre del tipo de movimiento (Ingreso/Egreso).",
  "concepto_caja.n_concepto": "Nombre del concepto de caja.",
  "concepto_caja.afecta_efectivo": "Indica si el concepto afecta el efectivo (S/N).",
  "serie_documento.tipo_documento": "Tipo de documento: 03=Boleta, 01=Factura, 07=Nota de crédito, TK=Ticket.",
  "serie_documento.serie": "Serie del comprobante (ej. B001, F001).",
  "serie_documento.correlativo": "Último correlativo emitido en la serie.",
  "venta.f_venta": "Fecha y hora de la venta.",
  "venta.tipodocumento": "Tipo de comprobante: 01=Factura, 03=Boleta, TK=Ticket.",
  "venta.subtotal": "Subtotal de la venta.",
  "venta.servicio": "Cargo por servicio de la venta.",
  "venta.igv": "IGV de la venta.",
  "venta.total": "Importe total de la venta.",
  "venta.total_pagado": "Importe recibido por la venta.",
  "venta.vuelto": "Vuelto entregado al cliente.",
  "venta.anulada": "Indica si la venta fue anulada (S/N).",
  "venta.motivo_anulacion": "Motivo de la anulación de la venta.",
  "detalle_venta.precio": "Precio unitario del producto en la venta.",
  "detalle_venta.sub_total": "Subtotal de la línea: (cantidad × precio) − descuento.",
  "boleta.serie": "Serie de la boleta (4 caracteres).",
  "boleta.numero": "Número correlativo de la boleta.",
  "boleta.f_emision": "Fecha y hora de emisión de la boleta.",
  "boleta.cliente_documento": "Documento del cliente (snapshot al momento de emitir).",
  "boleta.cliente_nombre": "Nombre del cliente (snapshot al momento de emitir).",
  "boleta.hash_cpe": "Hash del comprobante de pago electrónico.",
  "boleta.estado_sunat": "Estado SUNAT del comprobante (Pendiente/Aceptado/Rechazado).",
  "factura.serie": "Serie de la factura.",
  "factura.numero": "Número correlativo de la factura.",
  "factura.f_emision": "Fecha y hora de emisión de la factura.",
  "factura.f_vencimiento": "Fecha de vencimiento del crédito.",
  "factura.condicion_pago": "Condición de pago (Contado / Crédito).",
  "factura.orden_compra": "Orden de compra del cliente.",
  "factura.hash_cpe": "Hash del comprobante de pago electrónico.",
  "factura.estado_sunat": "Estado SUNAT del comprobante (Pendiente/Aceptado/Rechazado).",
  "factura.id_empresa": "Empresa receptora de la factura (con RUC).",
  "nota_credito.serie": "Serie de la nota de crédito.",
  "nota_credito.numero": "Número correlativo de la nota de crédito.",
  "nota_credito.tipo_doc_referencia": "Tipo de documento que se anula (01/03).",
  "nota_credito.serie_referencia": "Serie del comprobante que se anula.",
  "nota_credito.numero_referencia": "Número del comprobante que se anula.",
  "nota_credito.motivo": "Motivo de la emisión de la nota de crédito.",
  "nota_credito.monto": "Monto de la nota de crédito.",
  "nota_credito.f_emision": "Fecha y hora de emisión de la nota de crédito.",
  "nota_credito.estado_sunat": "Estado SUNAT del comprobante (Pendiente/Aceptado/Rechazado).",
  "pago_venta.monto": "Monto pagado con este método.",
  "pago_venta.referencia": "Referencia u operación del pago (ej. número de voucher).",
  "pago_venta.ultimos_digitos": "Últimos 4 dígitos de la tarjeta.",
  "pago_venta.f_pago": "Fecha y hora del pago.",
  "movimiento_caja.numero_operacion": "Número de operación bancaria o de la operación.",
  "movimiento_caja.documento": "Documento de respaldo del movimiento.",
  "movimiento_caja.descripcion": "Descripción del movimiento de caja.",
  "movimiento_caja.monto": "Monto del movimiento.",
  "movimiento_caja.afecta_efectivo": "Indica si el movimiento afecta el efectivo (S/N).",
  "movimiento_caja.f_movimiento": "Fecha y hora del movimiento.",
  "movimiento_caja.ip": "Dirección IP del movimiento.",
  "movimiento_caja.terminal": "Terminal del movimiento.",
  "receta.id_producto": "Producto preparado (el plato de la receta).",
  "receta.id_insumo": "Producto insumo que compone la receta.",
  "receta.cantidad": "Cantidad de insumo requerida por unidad de producto.",
  "movimiento_inventario.tipo_movimiento": "Tipo de movimiento: E=Entrada, S=Salida, A=Ajuste, M=Merma.",
  "movimiento_inventario.cantidad": "Cantidad movida del producto.",
  "movimiento_inventario.stock_anterior": "Stock del producto antes del movimiento.",
  "movimiento_inventario.stock_nuevo": "Stock del producto después del movimiento.",
  "movimiento_inventario.costo_unitario": "Costo unitario del producto en el movimiento.",
  "movimiento_inventario.documento": "Documento que originó el movimiento.",
  "movimiento_inventario.f_movimiento": "Fecha y hora del movimiento de inventario.",
};

// Descripciones de los objetos de código.
export const VISTAS = [
  ["vw_mapa_mesas", "Mapa de mesas del local con su ambiente, estado, color y el consumo del pedido abierto asociado."],
  ["vw_comanda_cocina", "Tablero de cocina: líneas de pedido pendientes o en proceso, con minutos de espera."],
  ["vw_ventas_diarias", "Resumen de ventas por fecha y tipo de comprobante (subtotal, IGV y total)."],
  ["vw_productos_mas_vendidos", "Ranking de productos más vendidos por cantidad e importe."],
  ["vw_arqueo_caja", "Arqueo de los turnos de caja con usuarios de apertura y cierre y su diferencia."],
  ["vw_clientes", "Listado unificado de clientes naturales y jurídicos, resolviendo nombre y documento."],
];

export const RUTINAS = [
  ["fn_total_pedido", "FUNCTION", "Calcula el total de un pedido sumando sus líneas no anuladas."],
  ["fn_login", "FUNCTION", "Valida login y clave (SHA-256), gestiona intentos/bloqueo y devuelve JSON. Espejo de usp_login."],
  ["fn_permisos_usuario", "FUNCTION", "Devuelve el conjunto de permisos efectivos de un usuario como arreglo JSON."],
  ["fn_cambiar_clave", "FUNCTION", "Cambia la contraseña del usuario desde su perfil validando la clave actual."],
  ["touch_audit", "FUNCTION", "Trigger que completa FECMOD automáticamente en cada UPDATE."],
  ["trg_producto_auditoria", "FUNCTION", "Trigger que registra en AUDITORIA los cambios del catálogo de productos."],
  ["trg_venta_auditoria", "FUNCTION", "Trigger que registra en AUDITORIA los cambios de total o anulación de una venta."],
  ["usp_login", "PROCEDURE", "Autentica al usuario, controla intentos y bloqueo, y registra el acceso en la auditoría."],
  ["usp_permisos_usuario", "PROCEDURE", "Entrega los permisos del usuario mediante refcursor, según roles vigentes."],
  ["usp_aperturar_caja", "PROCEDURE", "Abre un turno de caja con monto inicial y marca la caja como aperturada."],
  ["usp_registrar_movimiento_caja", "PROCEDURE", "Registra un movimiento de caja y actualiza los totales del turno."],
  ["usp_cerrar_caja", "PROCEDURE", "Cierra el turno, calcula la diferencia y devuelve el resultado del arqueo."],
  ["usp_abrir_pedido", "PROCEDURE", "Abre un pedido, valida la mesa y la marca como ocupada."],
  ["usp_recalcular_pedido", "PROCEDURE", "Recalcula subtotal, servicio, IGV y total del pedido."],
  ["usp_agregar_detalle_pedido", "PROCEDURE", "Agrega una línea al pedido y recalcula sus importes."],
  ["usp_facturar_pedido", "PROCEDURE", "Genera la venta, detalle, comprobante, pago y movimiento de caja; cierra el pedido."],
  ["usp_anular_pedido", "PROCEDURE", "Anula un pedido, libera la mesa y deja registro en la auditoría."],
  ["usp_anular_venta_con_nc", "PROCEDURE", "Anula una venta emitiendo nota de crédito y genera el egreso de caja."],
];

export const MODULO_DESC = {
  M01: "Catálogos geográficos (ubigeo).",
  M02: "Personas, empresas y clientes.",
  M03: "Recursos humanos del local.",
  M04: "Usuarios, roles, permisos y auditoría.",
  M05: "Salón, ambientes y mesas.",
  M06: "Carta de productos e inventarios.",
  M07: "Pedidos, comandas y reservas.",
  M08: "Delivery.",
  M09: "Caja y movimientos de efectivo.",
  M10: "Ventas y facturación electrónica.",
  M11: "Recetas y kardex de inventario.",
};